"""
style_gallery/presets.py - 预置风格数据（V0.4.6）

每条路线提供多个代表性预置风格，覆盖该路线的参数空间，用于探索"每种技术能做出
什么风格、风格跨度和能力边界"（宏观目标①②）。

从 router.py 抽出，便于扩充与测试。字段：
route_id / route_name / style_id / style_name / description / capabilities / tags / params
"""

from typing import Any

PRESET_STYLES: list[dict[str, Any]] = [
    # ──────────────── Pillow 信息卡路线 ────────────────
    {
        "route_id": "local_frame_compose",
        "route_name": "Pillow 信息卡路线",
        "style_id": "pillow_data_card",
        "style_name": "稳定数据卡",
        "description": "清晰展示数据指标，强调数字和来源，适合资讯类内容",
        "capabilities": ["长文本可读", "数据卡清楚", "排版稳定", "批量生成可靠"],
        "tags": ["数据", "资讯", "稳定"],
        "params": {
            "showDataViz": True, "highlightMode": "auto", "contentAlign": "center",
            "themeAdaptive": True, "transitionEnabled": True, "transitionFrames": 4,
            "titleColor": "#f8fafc", "bodyColor": "#94a3b8", "highlightColor": "#f59e0b",
        },
    },
    {
        "route_id": "local_frame_compose",
        "route_name": "Pillow 信息卡路线",
        "style_id": "pillow_minimal",
        "style_name": "极简资讯卡",
        "description": "极简排版，去除装饰，聚焦内容本身，适合深度阅读",
        "capabilities": ["极简排版", "聚焦内容", "无干扰"],
        "tags": ["极简", "深度阅读"],
        "params": {
            "showDataViz": False, "highlightMode": "numbers", "contentAlign": "center",
            "themeAdaptive": False, "transitionEnabled": False, "transitionFrames": 0,
            "titleColor": "#f8fafc", "bodyColor": "#cbd5e1", "highlightColor": "#22d3ee",
        },
    },
    {
        "route_id": "local_frame_compose",
        "route_name": "Pillow 信息卡路线",
        "style_id": "pillow_warm_editorial",
        "style_name": "暖色编辑风",
        "description": "固定暖色调 + 居中排版，杂志编辑质感，展示 Pillow 的品牌化定版能力",
        "capabilities": ["暖色品牌调", "居中编辑感", "固定风格（非自适应）"],
        "tags": ["暖色", "编辑", "品牌化"],
        "params": {
            "showDataViz": True, "highlightMode": "auto", "contentAlign": "center",
            "themeAdaptive": False, "transitionEnabled": True, "transitionFrames": 4,
            "titleColor": "#fff7ed", "bodyColor": "#fed7aa", "highlightColor": "#fb923c",
        },
    },

    {
        "route_id": "local_frame_compose",
        "route_name": "Pillow 信息卡路线",
        "style_id": "pillow_bold_contrast",
        "style_name": "高对比醒目卡",
        "description": "顶部对齐 + 红色强调 + 更强转场，醒目抢眼，适合需要冲击力的快讯",
        "capabilities": ["顶部对齐", "高对比红色强调", "强转场", "冲击力"],
        "tags": ["醒目", "高对比", "冲击"],
        "params": {
            "showDataViz": True, "highlightMode": "auto", "contentAlign": "top",
            "themeAdaptive": True, "transitionEnabled": True, "transitionFrames": 6,
            "titleColor": "#ffffff", "bodyColor": "#e2e8f0", "highlightColor": "#ef4444",
        },
    },
    {
        "route_id": "local_frame_compose",
        "route_name": "Pillow 信息卡路线",
        "style_id": "pillow_mono_serious",
        "style_name": "黑白严肃报",
        "description": "近黑白单色调 + 无数据图 + 无转场，严肃克制的报道感，展示去色端",
        "capabilities": ["单色调", "严肃克制", "无数据图", "无转场"],
        "tags": ["黑白", "严肃", "克制"],
        "params": {
            "showDataViz": False, "highlightMode": "numbers", "contentAlign": "center",
            "themeAdaptive": False, "transitionEnabled": False, "transitionFrames": 0,
            "titleColor": "#f1f5f9", "bodyColor": "#cbd5e1", "highlightColor": "#e2e8f0",
        },
    },

    # ──────────────── Remotion 动态模板路线 ────────────────
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_metric_motion",
        "style_name": "动态数据栏目",
        "description": "数字滚动 + 进度条生长，展示 Remotion 时间轴动画能力，适合数据驱动内容",
        "capabilities": ["数字滚动", "进度条生长", "卡片入场", "页面转场", "栏目包装感", "轻背景音"],
        "tags": ["动态", "数据", "栏目包装", "BGM"],
        "params": {
            "showDataViz": True, "accentColor": "#3b82f6", "highlightColor": "#f59e0b",
            "fontScale": 1, "showIcon": True, "motionIntensity": "medium",
            "coverStyle": "editorial", "overviewStyle": "timeline",
            "metricAnimation": "countup_bar", "transitionStyle": "slide_fade",
            "bgm": {"mode": "generated_ambient", "volume": 0.06, "fadeIn": 1.2, "fadeOut": 1.5},
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_cinematic",
        "style_name": "电影感快讯",
        "description": "电影感配色 + 慢速转场，营造大屏资讯氛围，适合重点报道",
        "capabilities": ["电影感", "慢速转场", "大屏氛围", "重点报道"],
        "tags": ["电影感", "大屏", "重点"],
        "params": {
            "showDataViz": True, "accentColor": "#a78bfa", "highlightColor": "#fbbf24",
            "fontScale": 1.1, "showIcon": False, "motionIntensity": "low",
            "coverStyle": "cinematic", "overviewStyle": "grid",
            "metricAnimation": "countup_number", "transitionStyle": "fade",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_minimal_clean",
        "style_name": "极简动效",
        "description": "克制的动效 + 干净排版，去掉数字动画和图标，展示 Remotion 低强度端的一面",
        "capabilities": ["克制动效", "干净排版", "无数字动画", "低干扰"],
        "tags": ["极简", "克制", "干净"],
        "params": {
            "showDataViz": False, "accentColor": "#60a5fa", "highlightColor": "#93c5fd",
            "fontScale": 1.05, "showIcon": False, "motionIntensity": "low",
            "coverStyle": "minimal", "overviewStyle": "clean",
            "metricAnimation": "none", "transitionStyle": "fade",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_high_energy",
        "style_name": "高能快剪",
        "description": "高强度动效 + 滑动转场 + 数字滚动，节奏强烈，展示 Remotion 动效上限",
        "capabilities": ["高强度动效", "滑动转场", "数字滚动", "强节奏"],
        "tags": ["高能", "快剪", "强动效"],
        "params": {
            "showDataViz": True, "accentColor": "#22c55e", "highlightColor": "#f59e0b",
            "fontScale": 1, "showIcon": True, "motionIntensity": "high",
            "coverStyle": "editorial", "overviewStyle": "timeline",
            "metricAnimation": "countup_bar", "transitionStyle": "slide",
            "bgm": {"mode": "generated_ambient", "volume": 0.07, "fadeIn": 1.0, "fadeOut": 1.2},
        },
    },

    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_card_stack",
        "style_name": "卡片叠层",
        "description": "采用 Card Stack 表现范式（与默认 Data News 完全不同的版式），卡片堆叠呈现，结构感强",
        "capabilities": ["卡片叠层版式", "区别于数据栏目", "结构感", "层次呈现"],
        "tags": ["卡片叠层", "版式差异", "结构"],
        "params": {
            "showDataViz": True, "accentColor": "#38bdf8", "highlightColor": "#fbbf24",
            "fontScale": 1, "showIcon": True, "motionIntensity": "medium",
            "coverStyle": "editorial", "overviewStyle": "timeline",
            "metricAnimation": "countup_bar", "transitionStyle": "slide_fade",
            "remotionFamily": "card_stack",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_neon_grid",
        "style_name": "霓虹网格",
        "description": "品红霓虹配色 + 网格总览 + 大字号 + 高强度动效，潮流社媒风，展示彩色高能端",
        "capabilities": ["霓虹配色", "网格总览", "大字号", "高强度动效"],
        "tags": ["霓虹", "网格", "潮流", "高能"],
        "params": {
            "showDataViz": True, "accentColor": "#ec4899", "highlightColor": "#a78bfa",
            "fontScale": 1.15, "showIcon": True, "motionIntensity": "high",
            "coverStyle": "cinematic", "overviewStyle": "grid",
            "metricAnimation": "countup_bar", "transitionStyle": "slide",
        },
    },
    {
        # V0.8.9: Timeline News 表现范式 — 把 keyPoints 映射成事件演进节点
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_timeline_news",
        "style_name": "时间线快讯",
        "description": "采用 Timeline News 表现范式，把 keyPoints 映射成事件演进节点，适合 AI 新闻、产品发布、研究进展类内容",
        "capabilities": ["事件演进时间线", "节点高亮切换", "进度线", "区别于数据栏目和卡片叠层", "适合新闻/产品发布"],
        "tags": ["时间线", "事件演进", "节点", "范式差异"],
        "params": {
            "showDataViz": True,
            "accentColor": "#0ea5e9",
            "highlightColor": "#22d3ee",
            "fontScale": 1,
            "showIcon": True,
            "motionIntensity": "medium",
            "coverStyle": "editorial",
            "overviewStyle": "timeline",
            "metricAnimation": "countup_number",
            "transitionStyle": "slide_fade",
            "remotionFamily": "timeline_news",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_dashboard_brief",
        "style_name": "指标看板快报",
        "description": "采用 Dashboard Brief 表现范式，把 keyPoints 映射为指标卡、活动信号和排行列表，适合 Benchmark、模型对比和高信息密度摘要。",
        "capabilities": ["指标看板", "排行列表", "活动信号", "高信息密度", "区别于卡片/时间线"],
        "tags": ["看板", "指标", "排行", "范式差异"],
        "params": {
            "showDataViz": True,
            "accentColor": "#f59e0b",
            "highlightColor": "#fde047",
            "fontScale": 0.95,
            "showIcon": True,
            "motionIntensity": "medium",
            "coverStyle": "minimal",
            "overviewStyle": "grid",
            "metricAnimation": "countup_number",
            "transitionStyle": "fade",
            "remotionFamily": "dashboard_brief",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_timeline_route_map",
        "style_name": "路线图时间线",
        "description": "采用 Timeline Route Map 变体，把 keyPoints 排成横向路线节点，适合路线、路径、产品推进和阶段式进展。",
        "capabilities": ["横向路线图", "节点推进", "路径展示", "阶段进展"],
        "tags": ["路线图", "时间线", "路径", "范式变体"],
        "params": {
            "showDataViz": True,
            "accentColor": "#0891b2",
            "highlightColor": "#67e8f9",
            "fontScale": 0.95,
            "showIcon": True,
            "motionIntensity": "medium",
            "coverStyle": "editorial",
            "overviewStyle": "timeline",
            "metricAnimation": "countup_number",
            "transitionStyle": "slide_fade",
            "remotionFamily": "timeline_news",
            "familyVariant": "route_map",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_chart_story",
        "style_name": "图表叙事",
        "description": "采用 Chart Story 变体，把 keyPoints 映射为逐步激活的柱状图和当前解读，适合 Benchmark、增长率、通过率类内容。",
        "capabilities": ["柱状图叙事", "当前柱高亮", "指标推进", "适合 Benchmark"],
        "tags": ["图表", "数据", "Benchmark", "范式变体"],
        "params": {
            "showDataViz": True,
            "accentColor": "#2563eb",
            "highlightColor": "#60a5fa",
            "fontScale": 0.95,
            "showIcon": True,
            "motionIntensity": "medium",
            "coverStyle": "minimal",
            "overviewStyle": "grid",
            "metricAnimation": "countup_number",
            "transitionStyle": "fade",
            "remotionFamily": "dashboard_brief",
            "familyVariant": "chart_story",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_ranking_strip",
        "style_name": "排行条快报",
        "description": "采用 Ranking Strip 变体，以大排行编号和横向强弱条呈现多条 AI 信号，适合 Top list、模型排行、工具推荐。",
        "capabilities": ["排行条", "Top list", "横向强弱条", "高扫读性"],
        "tags": ["排行", "榜单", "Top", "范式变体"],
        "params": {
            "showDataViz": True,
            "accentColor": "#22c55e",
            "highlightColor": "#86efac",
            "fontScale": 0.95,
            "showIcon": True,
            "motionIntensity": "medium",
            "coverStyle": "minimal",
            "overviewStyle": "grid",
            "metricAnimation": "countup_number",
            "transitionStyle": "fade",
            "remotionFamily": "dashboard_brief",
            "familyVariant": "ranking_strip",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_caption_story",
        "style_name": "大字旁白叙事",
        "description": "采用 Caption Story 表现范式，以大字号标题、旁白节奏和进度条推进内容，适合观点短片、口播摘要和情绪化解释。",
        "capabilities": ["大字标题", "旁白节奏", "进度条叙事", "情绪化表达", "区别于数据看板"],
        "tags": ["大字", "旁白", "叙事", "范式差异"],
        "params": {
            "showDataViz": False,
            "accentColor": "#ec4899",
            "highlightColor": "#f9a8d4",
            "fontScale": 1.05,
            "showIcon": False,
            "motionIntensity": "low",
            "coverStyle": "cinematic",
            "overviewStyle": "clean",
            "metricAnimation": "none",
            "transitionStyle": "fade",
            "remotionFamily": "caption_story",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_caption_intro",
        "style_name": "电影感开场字幕",
        "description": "采用 Caption Intro 变体，把每个 keyPoint 做成居中大标题开场感，适合科技发布、品牌感短片和重点观点开场。",
        "capabilities": ["居中大标题", "电影感开场", "弱化信息卡", "观点强化"],
        "tags": ["开场", "大字", "电影感", "范式变体"],
        "params": {
            "showDataViz": False,
            "accentColor": "#a855f7",
            "highlightColor": "#f0abfc",
            "fontScale": 1.0,
            "showIcon": False,
            "motionIntensity": "low",
            "coverStyle": "cinematic",
            "overviewStyle": "clean",
            "metricAnimation": "none",
            "transitionStyle": "fade",
            "remotionFamily": "caption_story",
            "familyVariant": "caption_intro",
        },
    },
    {
        "route_id": "template_programmatic_render",
        "route_name": "Remotion 动态模板路线",
        "style_id": "remotion_cta_overlay",
        "style_name": "行动号召叠层",
        "description": "采用 CTA Overlay 变体，在大字叙事底部叠加行动号召条，适合结尾引导、系列内容预告和社媒传播。",
        "capabilities": ["CTA 叠层", "结尾引导", "社媒传播", "大字叙事"],
        "tags": ["CTA", "叠层", "社媒", "范式变体"],
        "params": {
            "showDataViz": False,
            "accentColor": "#f43f5e",
            "highlightColor": "#fda4af",
            "fontScale": 1.0,
            "showIcon": False,
            "motionIntensity": "medium",
            "coverStyle": "cinematic",
            "overviewStyle": "clean",
            "metricAnimation": "none",
            "transitionStyle": "fade",
            "remotionFamily": "caption_story",
            "familyVariant": "cta_overlay",
        },
    },

    # ──────────────── AI 素材氛围路线 ────────────────
    {
        "route_id": "ai_asset_then_compose",
        "route_name": "AI 素材氛围路线",
        "style_id": "ai_asset_tech_mood",
        "style_name": "深蓝科技氛围",
        "description": "AI 生成深蓝科技背景 + 信息卡融合，传播型视觉，适合前沿资讯",
        "capabilities": ["AI 背景", "科技感氛围", "封面感", "背景+信息卡融合", "传播型视觉", "轻背景音"],
        "tags": ["科技", "氛围", "传播", "BGM"],
        "params": {
            "showDataViz": True,
            "imageStyle": "深蓝科技数据可视化背景，未来感，抽象光线，电影质感，无文字，无文本，柔和景深",
            "backgroundDarken": 0.55, "cardOpacity": 0.85, "cardBlur": True,
            "highlightColor": "#f59e0b", "contentAlign": "top", "kenBurns": True,
            "bgm": {"mode": "generated_ambient", "volume": 0.06, "fadeIn": 1.2, "fadeOut": 1.5},
        },
    },
    {
        "route_id": "ai_asset_then_compose",
        "route_name": "AI 素材氛围路线",
        "style_id": "ai_asset_cinematic",
        "style_name": "电影感光线背景",
        "description": "暖色调电影感光线背景 + 高对比度信息卡，适合深度分析和专题报道",
        "capabilities": ["电影感光线", "高对比度信息卡", "深度分析", "专题报道"],
        "tags": ["电影感", "光线", "深度"],
        "params": {
            "showDataViz": True,
            "imageStyle": "暖色调电影感光线背景，柔和散景，戏剧性光照，无文字，无文本，电影质感",
            "backgroundDarken": 0.6, "cardOpacity": 0.9, "cardBlur": False,
            "highlightColor": "#fbbf24", "contentAlign": "center", "kenBurns": True,
        },
    },
    {
        "route_id": "ai_asset_then_compose",
        "route_name": "AI 素材氛围路线",
        "style_id": "ai_asset_minimal_dark",
        "style_name": "极简暗调氛围",
        "description": "极简深色抽象背景 + 大量留白 + 静态稳定，展示 AI 素材路线的克制端",
        "capabilities": ["极简暗调", "大量留白", "静态稳定", "高级感"],
        "tags": ["极简", "暗调", "静态"],
        "params": {
            "showDataViz": False,
            "imageStyle": "极简深色抽象几何背景，大量留白，柔和光晕，高级感，无文字，无文本",
            "backgroundDarken": 0.5, "cardOpacity": 0.78, "cardBlur": True,
            "highlightColor": "#22d3ee", "contentAlign": "center", "kenBurns": False,
        },
    },
    {
        "route_id": "ai_asset_then_compose",
        "route_name": "AI 素材氛围路线",
        "style_id": "ai_warm_illustration",
        "style_name": "暖色手绘插画",
        "description": "AI 生成暖色手绘插画背景 + 信息卡，温暖治愈感，区别于科技冷调，适合人文向内容",
        "capabilities": ["手绘插画背景", "暖色治愈", "人文感", "区别于科技冷调"],
        "tags": ["手绘", "暖色", "人文"],
        "params": {
            "showDataViz": True,
            "imageStyle": "暖色手绘插画风格背景，柔和笔触，温暖治愈的色调，简约构图，无文字，无文本",
            "backgroundDarken": 0.5, "cardOpacity": 0.88, "cardBlur": False,
            "highlightColor": "#fb7185", "contentAlign": "center", "kenBurns": True,
        },
    },
    {
        "route_id": "ai_asset_then_compose",
        "route_name": "AI 素材氛围路线",
        "style_id": "ai_neon_cyber",
        "style_name": "赛博霓虹",
        "description": "AI 生成赛博朋克霓虹夜景背景 + 信息卡，紫粉蓝高饱和氛围，潮流冲击力强",
        "capabilities": ["赛博霓虹背景", "高饱和氛围", "潮流冲击", "夜景质感"],
        "tags": ["赛博", "霓虹", "潮流"],
        "params": {
            "showDataViz": True,
            "imageStyle": "赛博朋克霓虹城市夜景虚化背景，紫粉蓝霓虹光，未来都市氛围，无文字，无文本",
            "backgroundDarken": 0.62, "cardOpacity": 0.82, "cardBlur": True,
            "highlightColor": "#22d3ee", "contentAlign": "top", "kenBurns": True,
        },
    },
]


def list_preset_styles() -> list[dict[str, Any]]:
    """返回所有预置风格（每条路线多个，覆盖参数空间）。"""
    return PRESET_STYLES
